import { sql } from 'drizzle-orm'
import {
  boolean,
  customType,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  serial,
  text,
  timestamp,
  uniqueIndex,
} from 'drizzle-orm/pg-core'

/** Postgres' full-text search vector type; drizzle-orm has no built-in column for it. */
const tsvector = customType<{ data: string }>({
  dataType() {
    return 'tsvector'
  },
})

export const paperState = pgEnum('paper_state', [
  'unread',
  'read',
  'saved',
  'dismissed',
])

export const runStatus = pgEnum('run_status', [
  'running',
  'completed',
  'partial',
  'failed',
])

/** Whether an expression was generated by the model or written by hand. */
export const querySource = pgEnum('query_source', ['llm', 'manual'])

/**
 * A saved research interest. `description` is the natural-language query the
 * user wrote; the arXiv search expressions derived from it live in
 * `topic_queries` so that each can carry its own watermark.
 */
export const topics = pgTable('topics', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  description: text('description').notNull(),
  active: boolean('active').notNull().default(true),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
})

/**
 * One arXiv search expression belonging to a topic.
 *
 * The watermark lives here, not on the topic. A query added or edited later has
 * no watermark and therefore backfills on its next run, while its siblings keep
 * their progress and fetch only what is new. Were the watermark topic-level, a
 * newly added query would inherit it and silently never see any paper submitted
 * before the day it was created.
 */
export const topicQueries = pgTable(
  'topic_queries',
  {
    id: serial('id').primaryKey(),
    topicId: integer('topic_id')
      .notNull()
      .references(() => topics.id, { onDelete: 'cascade' }),
    expression: text('expression').notNull(),
    source: querySource('source').notNull().default('llm'),
    /** Model that produced this expression, when `source` is `llm`. */
    model: text('model'),
    /** Newest submittedDate already ingested through this expression. */
    lastFetchedAt: timestamp('last_fetched_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('topic_queries_topic_expression_idx').on(t.topicId, t.expression),
    index('topic_queries_topic_idx').on(t.topicId),
  ],
)

/**
 * A paper, shared across topics. `arxivId` is version-stripped (2401.12345) so
 * a resubmission dedupes onto the same row; `version` tracks the latest seen.
 */
export const papers = pgTable(
  'papers',
  {
    id: serial('id').primaryKey(),
    arxivId: text('arxiv_id').notNull(),
    version: integer('version').notNull().default(1),
    title: text('title').notNull(),
    abstract: text('abstract').notNull(),
    authors: jsonb('authors').$type<string[]>().notNull().default([]),
    categories: jsonb('categories').$type<string[]>().notNull().default([]),
    publishedAt: timestamp('published_at', { withTimezone: true }).notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull(),
    pdfUrl: text('pdf_url'),
    absUrl: text('abs_url').notNull(),
    /** Sentence embedding of title+abstract, used to score relevance against a topic's description. */
    embedding: jsonb('embedding').$type<number[]>(),
    /** Generated from title (weighted higher) and abstract, for full-text search within a topic. */
    searchVector: tsvector('search_vector')
      .notNull()
      .generatedAlwaysAs(
        sql`setweight(to_tsvector('english', coalesce(title, '')), 'A') || setweight(to_tsvector('english', coalesce(abstract, '')), 'B')`,
      ),
  },
  (t) => [
    uniqueIndex('papers_arxiv_id_idx').on(t.arxivId),
    index('papers_search_vector_idx').using('gin', t.searchVector),
  ],
)

/** Audit trail for ingestion runs, including where a budget-truncated run stopped. */
export const ingestRuns = pgTable('ingest_runs', {
  id: serial('id').primaryKey(),
  startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
  finishedAt: timestamp('finished_at', { withTimezone: true }),
  status: runStatus('status').notNull().default('running'),
  topicsProcessed: integer('topics_processed').notNull().default(0),
  papersFound: integer('papers_found').notNull().default(0),
  error: text('error'),
  /** Topic id the next run should start from when this one ran out of time. */
  resumeCursor: integer('resume_cursor'),
})

/**
 * Per-topic view of a paper: how it was found, how relevant it is, and whether
 * the user has dealt with it. A paper is a shared fact; its relevance is not.
 */
export const topicPapers = pgTable(
  'topic_papers',
  {
    id: serial('id').primaryKey(),
    topicId: integer('topic_id')
      .notNull()
      .references(() => topics.id, { onDelete: 'cascade' }),
    paperId: integer('paper_id')
      .notNull()
      .references(() => papers.id, { onDelete: 'cascade' }),
    firstSeenAt: timestamp('first_seen_at', { withTimezone: true }).notNull().defaultNow(),
    /** The ingest run that linked this paper to the topic — powers the "New" tab. Null for links that predate this column. */
    firstSeenRunId: integer('first_seen_run_id').references(() => ingestRuns.id),
    /** Cosine similarity between the topic's description and the paper's embedding, rescaled to 0-100. */
    relevanceScore: integer('relevance_score'),
    /** Which expanded query surfaced this paper — used to debug bad expansions. */
    matchedQuery: text('matched_query'),
    state: paperState('state').notNull().default('unread'),
    /** Freeform tag the user assigns, scoped to this topic's view of the paper. */
    label: text('label'),
    /** Freeform notes the user writes about the paper, scoped to this topic's view of it. */
    notes: text('notes'),
  },
  (t) => [
    uniqueIndex('topic_papers_topic_paper_idx').on(t.topicId, t.paperId),
    index('topic_papers_topic_state_idx').on(t.topicId, t.state),
    index('topic_papers_topic_run_idx').on(t.topicId, t.firstSeenRunId),
  ],
)

export type Topic = typeof topics.$inferSelect
export type NewTopic = typeof topics.$inferInsert
export type TopicQuery = typeof topicQueries.$inferSelect
export type NewTopicQuery = typeof topicQueries.$inferInsert
export type Paper = typeof papers.$inferSelect
export type NewPaper = typeof papers.$inferInsert
export type TopicPaper = typeof topicPapers.$inferSelect
export type IngestRun = typeof ingestRuns.$inferSelect
